server.port=5000

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/minidoctoplus

# JWT Configurations
doctoplus.jwt.secret=doctoplus_secret_key_2026_super_secure_987654321_spring
doctoplus.jwt.expiration=2592000000

# Swagger / OpenAPI (http://localhost:5000/swagger-ui/index.html)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Logging Options
logging.level.org.springframework.web=INFO
logging.level.com.doctoplus.backend=DEBUG
