server.port=5000

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/minidoctoplus

# JWT Configurations
doctoplus.jwt.secret=doctoplus_secret_key_2026_super_secure_987654321_spring
doctoplus.jwt.expiration=2592000000

# Logging Options
logging.level.org.springframework.web=INFO
logging.level.com.doctoplus.backend=DEBUG
